{
  "openapi": "3.0.1",
  "info": {
    "title": "RoR Base Template",
    "version": "v1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "Root Path",
        "tags": [
          "Application"
        ],
        "responses": {
          "200": {
            "description": "Root",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                }
              }
            }
          }
        }
      }
    },
    "/heartbeat": {
      "get": {
        "summary": "Heartbeat Path",
        "tags": [
          "Application"
        ],
        "responses": {
          "200": {
            "description": "Heartbeat",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                }
              }
            }
          }
        }
      }
    },
    "/error": {
      "get": {
        "summary": "Error Path",
        "tags": [
          "Application"
        ],
        "responses": {
          "422": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/auth/check": {
      "get": {
        "summary": "Check if User is Signed In",
        "tags": [
          "Authentication"
        ],
        "responses": {
          "200": {
            "description": "User is Signed In"
          },
          "401": {
            "description": "Unauthenticated",
            "content": {
              "application/json": {
                "examples": {
                  "key": {
                    "value": {
                      "message": "Unauthorized",
                      "errors": [
                        "A List of Errors"
                      ],
                      "context": {
                        "some": "Error Information"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/auth/refresh": {
      "get": {
        "summary": "Refresh User Token",
        "tags": [
          "Authentication"
        ],
        "responses": {
          "200": {
            "description": "Auth Cookies Refreshed"
          },
          "401": {
            "description": "Unauthenticated",
            "content": {
              "application/json": {
                "examples": {
                  "key": {
                    "value": {
                      "message": "Unauthorized",
                      "errors": [
                        "A List of Errors"
                      ],
                      "context": {
                        "some": "Error Information"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/auth/signin": {
      "post": {
        "summary": "Sign In User",
        "tags": [
          "Authentication"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "User Signed In",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "Bad Params",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Signin Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          },
          "required": true
        }
      }
    },
    "/auth/signup": {
      "post": {
        "summary": "Create a User",
        "tags": [
          "Authentication"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "Bad Params",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Could not create Profile",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "email",
                  "username",
                  "password"
                ]
              }
            }
          },
          "required": true
        }
      }
    },
    "/auth/signout": {
      "delete": {
        "summary": "Sign Out User",
        "tags": [
          "Authentication"
        ],
        "responses": {
          "204": {
            "description": "User Signed Out"
          },
          "401": {
            "description": "Unauthenticated",
            "content": {
              "application/json": {
                "examples": {
                  "key": {
                    "value": {
                      "message": "Unauthorized",
                      "errors": [
                        "A List of Errors"
                      ],
                      "context": {
                        "some": "Error Information"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    },
    "/user": {
      "delete": {
        "summary": "delete current user",
        "tags": [
          "User"
        ],
        "responses": {
          "204": {
            "description": "no content"
          },
          "404": {
            "description": "user not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthenticated",
            "content": {
              "application/json": {
                "examples": {
                  "key": {
                    "value": {
                      "message": "Unauthorized",
                      "errors": [
                        "A List of Errors"
                      ],
                      "context": {
                        "some": "Error Information"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://localhost:3001"
    }
  ],
  "components": {
    "schemas": {
      "SuccessResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "success"
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "data": {
            "type": "object",
            "description": "Payload containing data"
          }
        },
        "required": [
          "status",
          "message",
          "data"
        ]
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "error"
          },
          "message": {
            "type": "string",
            "example": "Error"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "string",
              "example": "Transaction failed"
            }
          }
        },
        "required": [
          "status",
          "message",
          "errors"
        ]
      },
      "User": {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "uuid": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "username": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "uuid",
              "email",
              "username"
            ]
          }
        }
      }
    },
    "responses": {
      "Success": {
        "description": "Generic success response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SuccessResponse"
            }
          }
        }
      },
      "ValidationError": {
        "description": "Validation or invalid input error response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "NotFoundError": {
        "description": "Resource not found error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "ServerError": {
        "description": "Internal server error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      },
      "UnauthorizedError": {
        "description": "Unauthorized error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      }
    }
  }
}